package com.apixenglish.center.modules.videodelivery.service;
import com.apixenglish.center.common.exception.*; import com.apixenglish.center.common.response.PageResponse;
import com.apixenglish.center.modules.audit.service.AuditService; import com.apixenglish.center.modules.classmanagement.entity.*;
import com.apixenglish.center.modules.classmanagement.repository.*; import com.apixenglish.center.modules.classmanagement.service.ClassScopeGuard;
import com.apixenglish.center.modules.employee.entity.Employee; import com.apixenglish.center.modules.media.entity.VideoType;
import com.apixenglish.center.modules.parent.entity.Parent; import com.apixenglish.center.modules.student.entity.*;
import com.apixenglish.center.modules.student.repository.*; import com.apixenglish.center.modules.videodelivery.dto.VideoDeliveryDtos.*;
import com.apixenglish.center.modules.videodelivery.entity.*; import com.apixenglish.center.modules.videodelivery.repository.*;
import com.apixenglish.center.security.CurrentActor; import jakarta.persistence.criteria.*; import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification; import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional; import org.springframework.util.StringUtils;
import java.time.*; import java.time.format.DateTimeFormatter; import java.util.*;

@Service @RequiredArgsConstructor
public class VideoDeliveryService {
 private static final String MODULE="VIDEO_DELIVERY";
 private final VideoDeliveryBatchRepository batches; private final StudentVideoDeliveryRepository deliveries;
 private final VideoDeliveryAttemptRepository attempts; private final ClazzRepository classes; private final StudentRepository students;
 private final ClassEnrollmentRepository enrollments; private final StudentParentRepository studentParents;
 private final ClassScopeGuard scope; private final CurrentActor actor; private final AuditService audit;

 @Transactional public BatchItem createBatch(CreateBatch request){
  validateMonth(request.videoType(),request.targetMonth()); Clazz clazz=request.classId()==null?null:findClass(request.classId());
  List<Student> targets=resolveTargets(clazz,request.studentIds()); if(targets.isEmpty())throw new BusinessException("No active students were selected","VIDEO_DELIVERY_TARGETS_EMPTY");
  Employee employee=scope.currentEmployee(); VideoDeliveryBatch batch=VideoDeliveryBatch.builder().clazz(clazz).videoType(request.videoType()).targetMonth(request.targetMonth()).title(request.title()).description(request.description()).dueDate(request.dueDate()).status(VideoBatchStatus.ACTIVE).createdByEmployee(employee).build();
  batch=batches.save(batch); for(Student student:targets){Parent parent=preferredParent(student.getId());deliveries.save(StudentVideoDelivery.builder().batch(batch).student(student).clazz(clazz).parent(parent).videoType(request.videoType()).targetMonth(request.targetMonth()).title(request.title()).messageContent(message(request.videoType(),request.targetMonth(),student.getFullName())).channel(VideoDeliveryChannel.MANUAL_ZALO_DIRECT).status(VideoDeliveryStatus.PENDING).assignedToEmployee(employee).build());}
  audit.record("VIDEO_DELIVERY_BATCH_CREATED",MODULE,"VideoDeliveryBatch",batch.getId(),null,Map.of("status","ACTIVE","deliveries",targets.size()));return batchItem(batch);
 }

 @Transactional(readOnly=true) public PageResponse<BatchItem> listBatches(String search,UUID classId,VideoType type,LocalDate month,VideoBatchStatus status,LocalDate dueFrom,LocalDate dueTo,Pageable pageable){
  Specification<VideoDeliveryBatch> spec=batchSpec(search,classId,type,month,status,dueFrom,dueTo);return PageResponse.of(batches.findAll(spec,pageable).map(this::batchItem));
 }
 @Transactional public BatchItem updateBatch(UUID id,UpdateBatch request){VideoDeliveryBatch b=findBatch(id);if(b.getStatus()==VideoBatchStatus.CANCELLED)throw new ConflictException("Cancelled batch cannot be updated");if(request.status()==VideoBatchStatus.CANCELLED)throw new BusinessException("Use the cancel endpoint so open deliveries are cancelled","USE_BATCH_CANCEL_ENDPOINT");if(request.status()==VideoBatchStatus.COMPLETED&&!allTerminal(b.getId()))throw new ConflictException("Batch still has unfinished deliveries","BATCH_NOT_COMPLETE");Map<String,Object> before=Map.of("status",b.getStatus().name(),"title",b.getTitle());b.setTitle(request.title());b.setDescription(request.description());b.setDueDate(request.dueDate());b.setStatus(request.status());b.setNote(request.note());b.setCompletedAt(request.status()==VideoBatchStatus.COMPLETED?Instant.now():null);batches.save(b);audit.record("VIDEO_DELIVERY_BATCH_UPDATED",MODULE,"VideoDeliveryBatch",id,before,Map.of("status",b.getStatus().name(),"title",b.getTitle()));return batchItem(b);}
 @Transactional public void cancelBatch(UUID id){VideoDeliveryBatch b=findBatch(id);if(b.getStatus()==VideoBatchStatus.CANCELLED)throw new ConflictException("Batch is already cancelled");b.setStatus(VideoBatchStatus.CANCELLED);b.setCompletedAt(null);for(StudentVideoDelivery d:deliveries.findByBatchIdAndDeletedAtIsNull(id))if(EnumSet.of(VideoDeliveryStatus.PENDING,VideoDeliveryStatus.PREPARED,VideoDeliveryStatus.OPENED_ZALO).contains(d.getStatus()))d.setStatus(VideoDeliveryStatus.CANCELLED);batches.save(b);audit.record("VIDEO_DELIVERY_BATCH_CANCELLED",MODULE,"VideoDeliveryBatch",id,null,Map.of("status","CANCELLED"));}

 @Transactional(readOnly=true) public PageResponse<DeliveryItem> listDeliveries(String search,UUID batchId,UUID classId,UUID studentId,UUID parentId,VideoType type,LocalDate month,VideoDeliveryStatus status,UUID assigned,UUID sentBy,Pageable pageable){return PageResponse.of(deliveries.findAll(deliverySpec(search,batchId,classId,studentId,parentId,type,month,status,assigned,sentBy),pageable).map(this::item));}
 @Transactional(readOnly=true) public DeliveryDetail detail(UUID id){StudentVideoDelivery d=findDelivery(id);enforceRead(d.getClazz());return detailOf(d);}

 @Transactional public PrepareMessageResponse prepare(UUID id){StudentVideoDelivery d=findDelivery(id);require(d,VideoDeliveryStatus.PENDING,VideoDeliveryStatus.PREPARED);Parent p=requireParent(d);String content=message(d.getVideoType(),d.getTargetMonth(),d.getStudent().getFullName());d.setMessageContent(content);d.setStatus(VideoDeliveryStatus.PREPARED);deliveries.save(d);addAttempt(d,VideoAttemptAction.PREPARED_MESSAGE,content,null);audit.record("VIDEO_DELIVERY_MESSAGE_PREPARED",MODULE,"StudentVideoDelivery",id,null,Map.of("status","PREPARED"));return new PrepareMessageResponse(id,p.getFullName(),p.getPhone(),"https://zalo.me/"+normalizePhone(p.getPhone()),content,d.getStatus());}
 @Transactional public DeliveryDetail copied(UUID id){StudentVideoDelivery d=findDelivery(id);require(d,VideoDeliveryStatus.PREPARED,VideoDeliveryStatus.OPENED_ZALO);addAttempt(d,VideoAttemptAction.COPIED_MESSAGE,d.getMessageContent(),null);return detailOf(d);}
 @Transactional public DeliveryDetail opened(UUID id){StudentVideoDelivery d=findDelivery(id);require(d,VideoDeliveryStatus.PREPARED,VideoDeliveryStatus.OPENED_ZALO);d.setStatus(VideoDeliveryStatus.OPENED_ZALO);deliveries.save(d);addAttempt(d,VideoAttemptAction.OPENED_ZALO,d.getMessageContent(),null);audit.record("VIDEO_DELIVERY_ZALO_OPENED",MODULE,"StudentVideoDelivery",id,null,Map.of("status","OPENED_ZALO"));return detailOf(d);}
 @Transactional public DeliveryDetail sent(UUID id,String note){StudentVideoDelivery d=findDelivery(id);require(d,VideoDeliveryStatus.PENDING,VideoDeliveryStatus.PREPARED,VideoDeliveryStatus.OPENED_ZALO);Employee e=scope.currentEmployee();d.setStatus(VideoDeliveryStatus.SENT_MANUALLY);d.setSentByEmployee(e);d.setSentAt(Instant.now());d.setFailedReason(null);d.setSkippedReason(null);d.setNote(note);deliveries.save(d);addAttempt(d,VideoAttemptAction.MARKED_SENT,d.getMessageContent(),note);completeBatchIfReady(d.getBatch());audit.record("VIDEO_DELIVERY_MARKED_SENT",MODULE,"StudentVideoDelivery",id,null,Map.of("status","SENT_MANUALLY"));return detailOf(d);}
 @Transactional public DeliveryDetail failed(UUID id,String reason){StudentVideoDelivery d=findDelivery(id);require(d,VideoDeliveryStatus.PENDING,VideoDeliveryStatus.PREPARED,VideoDeliveryStatus.OPENED_ZALO);d.setStatus(VideoDeliveryStatus.FAILED);d.setFailedReason(reason);deliveries.save(d);addAttempt(d,VideoAttemptAction.MARKED_FAILED,d.getMessageContent(),reason);audit.record("VIDEO_DELIVERY_MARKED_FAILED",MODULE,"StudentVideoDelivery",id,null,Map.of("status","FAILED","reason",reason));return detailOf(d);}
 @Transactional public DeliveryDetail skipped(UUID id,String reason){StudentVideoDelivery d=findDelivery(id);require(d,VideoDeliveryStatus.PENDING,VideoDeliveryStatus.PREPARED,VideoDeliveryStatus.OPENED_ZALO,VideoDeliveryStatus.FAILED);d.setStatus(VideoDeliveryStatus.SKIPPED);d.setSkippedReason(reason);deliveries.save(d);addAttempt(d,VideoAttemptAction.MARKED_SKIPPED,d.getMessageContent(),reason);completeBatchIfReady(d.getBatch());audit.record("VIDEO_DELIVERY_MARKED_SKIPPED",MODULE,"StudentVideoDelivery",id,null,Map.of("status","SKIPPED","reason",reason));return detailOf(d);}
 @Transactional public DeliveryDetail reopen(UUID id){StudentVideoDelivery d=findDelivery(id);require(d,VideoDeliveryStatus.FAILED,VideoDeliveryStatus.SKIPPED);d.setStatus(VideoDeliveryStatus.PENDING);d.setFailedReason(null);d.setSkippedReason(null);d.setSentByEmployee(null);d.setSentAt(null);deliveries.save(d);if(d.getBatch()!=null&&d.getBatch().getStatus()==VideoBatchStatus.COMPLETED){d.getBatch().setStatus(VideoBatchStatus.ACTIVE);d.getBatch().setCompletedAt(null);batches.save(d.getBatch());}addAttempt(d,VideoAttemptAction.REOPENED,d.getMessageContent(),null);audit.record("VIDEO_DELIVERY_REOPENED",MODULE,"StudentVideoDelivery",id,null,Map.of("status","PENDING"));return detailOf(d);}

 @Transactional(readOnly=true) public Stats stats(UUID classId,VideoType type,LocalDate month,LocalDate dueFrom,LocalDate dueTo){List<StudentVideoDelivery> values=deliveries.findAll(deliverySpec(null,null,classId,null,null,type,month,null,null,null)).stream().filter(d->d.getBatch()!=null&&(dueFrom==null||d.getBatch().getDueDate()!=null&&!d.getBatch().getDueDate().isBefore(dueFrom))&&(dueTo==null||d.getBatch().getDueDate()!=null&&!d.getBatch().getDueDate().isAfter(dueTo))).toList();long pending=count(values,VideoDeliveryStatus.PENDING),prepared=count(values,VideoDeliveryStatus.PREPARED),opened=count(values,VideoDeliveryStatus.OPENED_ZALO),sent=count(values,VideoDeliveryStatus.SENT_MANUALLY),failed=count(values,VideoDeliveryStatus.FAILED),skipped=count(values,VideoDeliveryStatus.SKIPPED);long overdue=values.stream().filter(d->d.getBatch().getDueDate()!=null&&d.getBatch().getDueDate().isBefore(LocalDate.now())&&!EnumSet.of(VideoDeliveryStatus.SENT_MANUALLY,VideoDeliveryStatus.SKIPPED,VideoDeliveryStatus.CANCELLED).contains(d.getStatus())).count();double rate=values.isEmpty()?0.0:Math.round(sent*10000.0/values.size())/100.0;return new Stats(values.size(),pending,prepared,opened,sent,failed,skipped,rate,overdue);}

 private Specification<VideoDeliveryBatch> batchSpec(String search,UUID classId,VideoType type,LocalDate month,VideoBatchStatus status,LocalDate from,LocalDate to){return(root,q,cb)->{List<Predicate>p=new ArrayList<>();p.add(cb.isNull(root.get("deletedAt")));if(StringUtils.hasText(search)){String x="%"+search.toLowerCase(Locale.ROOT)+"%";p.add(cb.or(cb.like(cb.lower(root.get("title")),x),cb.like(cb.lower(root.get("description")),x),cb.like(cb.lower(root.join("clazz",JoinType.LEFT).get("name")),x)));}if(classId!=null)p.add(cb.equal(root.get("clazz").get("id"),classId));if(type!=null)p.add(cb.equal(root.get("videoType"),type));if(month!=null)p.add(cb.equal(root.get("targetMonth"),month));if(status!=null)p.add(cb.equal(root.get("status"),status));if(from!=null)p.add(cb.greaterThanOrEqualTo(root.get("dueDate"),from));if(to!=null)p.add(cb.lessThanOrEqualTo(root.get("dueDate"),to));addClassScope(root,q,cb,p,"clazz");return cb.and(p.toArray(Predicate[]::new));};}
 private Specification<StudentVideoDelivery> deliverySpec(String search,UUID batchId,UUID classId,UUID studentId,UUID parentId,VideoType type,LocalDate month,VideoDeliveryStatus status,UUID assigned,UUID sentBy){return(root,q,cb)->{List<Predicate>p=new ArrayList<>();p.add(cb.isNull(root.get("deletedAt")));if(StringUtils.hasText(search)){String x="%"+search.toLowerCase(Locale.ROOT)+"%";p.add(cb.or(cb.like(cb.lower(root.get("title")),x),cb.like(cb.lower(root.join("student").get("fullName")),x),cb.like(cb.lower(root.join("student").get("studentCode")),x),cb.like(cb.lower(root.join("parent",JoinType.LEFT).get("fullName")),x)));}if(batchId!=null)p.add(cb.equal(root.get("batch").get("id"),batchId));if(classId!=null)p.add(cb.equal(root.get("clazz").get("id"),classId));if(studentId!=null)p.add(cb.equal(root.get("student").get("id"),studentId));if(parentId!=null)p.add(cb.equal(root.get("parent").get("id"),parentId));if(type!=null)p.add(cb.equal(root.get("videoType"),type));if(month!=null)p.add(cb.equal(root.get("targetMonth"),month));if(status!=null)p.add(cb.equal(root.get("status"),status));if(assigned!=null)p.add(cb.equal(root.get("assignedToEmployee").get("id"),assigned));if(sentBy!=null)p.add(cb.equal(root.get("sentByEmployee").get("id"),sentBy));addClassScope(root,q,cb,p,"clazz");return cb.and(p.toArray(Predicate[]::new));};}
 private <T> void addClassScope(Root<T> root,CriteriaQuery<?> q,CriteriaBuilder cb,List<Predicate>p,String field){if(isClassScoped()){Employee e=scope.currentEmployee();Subquery<UUID>sq=q.subquery(UUID.class);Root<ClassStaff>cs=sq.from(ClassStaff.class);sq.select(cs.get("clazz").get("id")).where(cb.equal(cs.get("employee").get("id"),e.getId()),cb.isNull(cs.get("deletedAt")),cb.lessThanOrEqualTo(cs.get("startDate"),LocalDate.now()),cb.or(cb.isNull(cs.get("endDate")),cb.greaterThanOrEqualTo(cs.get("endDate"),LocalDate.now())));p.add(root.get(field).get("id").in(sq));}}
 private boolean isClassScoped(){return !actor.has("video-delivery:create-batch")&&!actor.has("video-delivery:update-batch")&&!actor.has("*");}
 private void enforceRead(Clazz clazz){if(isClassScoped()){if(clazz==null)throw new ForbiddenException("Delivery is outside assigned class scope");scope.requireAssigned(clazz.getId());}}
 private List<Student> resolveTargets(Clazz clazz,List<UUID> ids){if(ids==null||ids.isEmpty()){if(clazz==null)throw new BusinessException("classId is required when studentIds is empty","VIDEO_DELIVERY_CLASS_REQUIRED");return enrollments.findByClazzIdAndStatusAndDeletedAtIsNull(clazz.getId(),"ACTIVE").stream().map(ClassEnrollment::getStudent).distinct().toList();}LinkedHashSet<UUID>unique=new LinkedHashSet<>(ids);List<Student>result=new ArrayList<>();for(UUID id:unique){Student s=students.findById(id).filter(x->x.getDeletedAt()==null).orElseThrow(()->new ResourceNotFoundException("Student not found: "+id));if(clazz!=null&&!enrollments.existsByStudentIdAndClazzIdAndStatusAndDeletedAtIsNull(id,clazz.getId(),"ACTIVE"))throw new BusinessException("Student is not active in selected class: "+id,"VIDEO_DELIVERY_STUDENT_CLASS_MISMATCH");result.add(s);}return result;}
 private Parent preferredParent(UUID studentId){return studentParents.findByStudentIdAndDeletedAtIsNull(studentId).stream().filter(x->Boolean.TRUE.equals(x.getCanReceiveNotification())).sorted(Comparator.comparing((StudentParent x)->!Boolean.TRUE.equals(x.getIsPrimaryContact()))).map(StudentParent::getParent).findFirst().orElse(null);}
 private Parent requireParent(StudentVideoDelivery d){if(d.getParent()==null)throw new BusinessException("No notification parent is assigned to this delivery","VIDEO_DELIVERY_PARENT_REQUIRED");if(!StringUtils.hasText(d.getParent().getPhone()))throw new BusinessException("Parent has no phone number","VIDEO_DELIVERY_PARENT_PHONE_REQUIRED");return d.getParent();}
 private void addAttempt(StudentVideoDelivery d,VideoAttemptAction action,String content,String note){Employee e=scope.currentEmployee();attempts.save(VideoDeliveryAttempt.builder().videoDelivery(d).action(action).actorEmployee(e).parent(d.getParent()).recipientPhone(d.getParent()==null?null:d.getParent().getPhone()).messageContent(content).note(note).build());}
 private void completeBatchIfReady(VideoDeliveryBatch b){if(b!=null&&b.getStatus()!=VideoBatchStatus.CANCELLED&&allTerminal(b.getId())){b.setStatus(VideoBatchStatus.COMPLETED);b.setCompletedAt(Instant.now());batches.save(b);}}
 private boolean allTerminal(UUID batchId){List<StudentVideoDelivery>all=deliveries.findByBatchIdAndDeletedAtIsNull(batchId);return !all.isEmpty()&&all.stream().allMatch(d->EnumSet.of(VideoDeliveryStatus.SENT_MANUALLY,VideoDeliveryStatus.SKIPPED,VideoDeliveryStatus.CANCELLED).contains(d.getStatus()));}
 private void require(StudentVideoDelivery d,VideoDeliveryStatus...allowed){if(Arrays.stream(allowed).noneMatch(x->x==d.getStatus()))throw new ConflictException("Delivery cannot transition from "+d.getStatus(),"VIDEO_DELIVERY_INVALID_TRANSITION");}
 void validateMonth(VideoType type,LocalDate month){if(type==VideoType.MONTHLY_PERSONAL_VIDEO&&month==null)throw new BusinessException("Monthly personal video requires targetMonth","VIDEO_DELIVERY_MONTH_REQUIRED");if(month!=null&&month.getDayOfMonth()!=1)throw new BusinessException("targetMonth must be the first day of the month","INVALID_TARGET_MONTH");}
 String message(VideoType type,LocalDate month,String student){String intro=switch(type){case MONTHLY_PERSONAL_VIDEO->"APIX English gửi phụ huynh video speaking tháng "+month.format(DateTimeFormatter.ofPattern("MM/yyyy"))+" của bé "+student+".";case FINAL_COURSE_VIDEO->"APIX English gửi phụ huynh video cuối khóa của bé "+student+".";case FOREIGN_TEACHER_ACTIVITY->"APIX English gửi phụ huynh video hoạt động với giáo viên nước ngoài của bé "+student+".";case CLASS_ACTIVITY_VIDEO->"APIX English gửi phụ huynh video hoạt động lớp của bé "+student+".";case CUSTOM->"APIX English gửi phụ huynh video của bé "+student+".";};return intro+"\nPhụ huynh xem video em gửi trực tiếp trong tin nhắn Zalo này nhé.\nTrân trọng,\nAPIX English";}
 private String normalizePhone(String phone){String value=phone.replaceAll("\\D","");if(value.startsWith("84"))return value;if(value.startsWith("0"))return "84"+value.substring(1);return value;}
 private Clazz findClass(UUID id){return classes.findById(id).filter(x->x.getDeletedAt()==null).orElseThrow(()->new ResourceNotFoundException("Class not found"));}
 private VideoDeliveryBatch findBatch(UUID id){return batches.findDetail(id).orElseThrow(()->new ResourceNotFoundException("Video delivery batch not found"));}
 private StudentVideoDelivery findDelivery(UUID id){return deliveries.findDetail(id).orElseThrow(()->new ResourceNotFoundException("Video delivery not found"));}
 private long count(List<StudentVideoDelivery>v,VideoDeliveryStatus s){return v.stream().filter(x->x.getStatus()==s).count();}
 private BatchItem batchItem(VideoDeliveryBatch b){UUID id=b.getId();return new BatchItem(id,b.getClazz()==null?null:b.getClazz().getId(),b.getClazz()==null?null:b.getClazz().getName(),b.getVideoType(),b.getTargetMonth(),b.getTitle(),b.getDescription(),b.getDueDate(),b.getStatus(),deliveries.findByBatchIdAndDeletedAtIsNull(id).size(),deliveries.countByBatchIdAndStatusAndDeletedAtIsNull(id,VideoDeliveryStatus.PENDING),deliveries.countByBatchIdAndStatusAndDeletedAtIsNull(id,VideoDeliveryStatus.SENT_MANUALLY),deliveries.countByBatchIdAndStatusAndDeletedAtIsNull(id,VideoDeliveryStatus.FAILED),deliveries.countByBatchIdAndStatusAndDeletedAtIsNull(id,VideoDeliveryStatus.SKIPPED),b.getCompletedAt(),b.getCreatedAt(),b.getUpdatedAt());}
 private DeliveryItem item(StudentVideoDelivery d){return new DeliveryItem(d.getId(),d.getBatch()==null?null:d.getBatch().getId(),d.getStudent().getId(),d.getStudent().getStudentCode(),d.getStudent().getFullName(),d.getClazz()==null?null:d.getClazz().getId(),d.getClazz()==null?null:d.getClazz().getName(),d.getParent()==null?null:d.getParent().getId(),d.getParent()==null?null:d.getParent().getFullName(),d.getParent()==null?null:d.getParent().getPhone(),d.getVideoType(),d.getTargetMonth(),d.getTitle(),d.getMessageContent(),d.getChannel(),d.getStatus(),d.getAssignedToEmployee()==null?null:d.getAssignedToEmployee().getFullName(),d.getSentByEmployee()==null?null:d.getSentByEmployee().getFullName(),d.getSentAt(),d.getFailedReason(),d.getSkippedReason(),d.getNote(),d.getCreatedAt(),d.getUpdatedAt());}
 private DeliveryDetail detailOf(StudentVideoDelivery d){List<AttemptItem>history=attempts.findHistory(d.getId()).stream().map(a->new AttemptItem(a.getId(),a.getAction(),a.getActorEmployee()==null?null:a.getActorEmployee().getId(),a.getActorEmployee()==null?null:a.getActorEmployee().getFullName(),a.getParent()==null?null:a.getParent().getId(),a.getRecipientPhone(),a.getMessageContent(),a.getNote(),a.getCreatedAt())).toList();return new DeliveryDetail(item(d),new StudentSummary(d.getStudent().getId(),d.getStudent().getStudentCode(),d.getStudent().getFullName()),d.getClazz()==null?null:new ClassSummary(d.getClazz().getId(),d.getClazz().getName()),d.getParent()==null?null:new ParentSummary(d.getParent().getId(),d.getParent().getFullName(),d.getParent().getPhone()),history,d.getVersion());}
}
