package com.apixenglish.center.modules.score.service;
import com.apixenglish.center.common.exception.*;import com.apixenglish.center.modules.audit.service.AuditService;import com.apixenglish.center.modules.classmanagement.entity.Clazz;import com.apixenglish.center.modules.classmanagement.repository.*;import com.apixenglish.center.modules.classmanagement.service.ClassScopeGuard;import com.apixenglish.center.modules.employee.entity.Employee;import com.apixenglish.center.modules.score.dto.ScoreDtos.*;import com.apixenglish.center.modules.score.entity.*;import com.apixenglish.center.modules.score.repository.ScoreItemRepository;import com.apixenglish.center.modules.student.entity.Student;import com.apixenglish.center.modules.student.repository.StudentRepository;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.Instant;import java.util.*;
@Service @RequiredArgsConstructor public class ScoreService {
 private final ScoreItemRepository repository;private final ClazzRepository classes;private final StudentRepository students;private final ClassEnrollmentRepository enrollments;private final ClassScopeGuard scope;private final AuditService audit;
 @Transactional public Response create(Upsert r){Employee e=scope.requireAssigned(r.classId());Clazz c=classes.findById(r.classId()).filter(x->x.getDeletedAt()==null).orElseThrow(()->new ResourceNotFoundException("Class not found"));ScoreItem i=repository.save(ScoreItem.builder().clazz(c).title(r.title()).maxScore(r.maxScore()).scoreDate(r.scoreDate()).note(r.note()).status(ScoreItemStatus.DRAFT).createdByEmployee(e).build());audit.record("SCORE_ITEM_CREATED","score","ScoreItem",i.getId(),null,Map.of("status","DRAFT"));return map(i);}
 @Transactional(readOnly=true) public Page<Response> list(UUID classId,Pageable p){return repository.findByClazzIdAndDeletedAtIsNull(classId,p).map(this::map);}
 @Transactional(readOnly=true) public Response get(UUID id){return map(find(id));}
 @Transactional public Response update(UUID id,Upsert r){ScoreItem i=find(id);scope.requireAssigned(i.getClazz().getId());draft(i);i.setTitle(r.title());i.setMaxScore(r.maxScore());i.setScoreDate(r.scoreDate());i.setNote(r.note());return map(repository.save(i));}
 @Transactional public Response records(UUID id,Records request){ScoreItem i=find(id);Employee grader=scope.requireAssigned(i.getClazz().getId());draft(i);Set<UUID> seen=new HashSet<>();i.getRecords().clear();for(RecordInput value:request.records()){if(!seen.add(value.studentId()))throw new BusinessException("A student can appear only once","DUPLICATE_SCORE_STUDENT");if(value.score().compareTo(i.getMaxScore())>0)throw new BusinessException("Score must not exceed maxScore","SCORE_EXCEEDS_MAX");if(!enrollments.existsByStudentIdAndClazzIdAndStatusAndDeletedAtIsNull(value.studentId(),i.getClazz().getId(),"ACTIVE"))throw new BusinessException("Student is not actively enrolled in this class","STUDENT_NOT_IN_CLASS");Student s=students.findById(value.studentId()).orElseThrow(()->new ResourceNotFoundException("Student not found"));i.getRecords().add(ScoreRecord.builder().scoreItem(i).student(s).score(value.score()).comment(value.comment()).gradedBy(grader).gradedAt(Instant.now()).build());}repository.save(i);audit.record("SCORES_RECORDED","score","ScoreItem",id,null,Map.of("recordCount",i.getRecords().size()));return map(i);}
 @Transactional public Response publish(UUID id){ScoreItem i=find(id);scope.requireAssigned(i.getClazz().getId());draft(i);if(i.getRecords().isEmpty())throw new BusinessException("At least one score record is required","SCORE_RECORDS_REQUIRED");i.setStatus(ScoreItemStatus.PUBLISHED);repository.save(i);audit.record("SCORE_PUBLISHED","score","ScoreItem",id,null,Map.of("status","PUBLISHED"));return map(i);}
 @Transactional public Response deliver(UUID id){ScoreItem i=find(id);if(i.getStatus()!=ScoreItemStatus.PUBLISHED)throw new ConflictException("Only a published score item can be delivered");i.setStatus(ScoreItemStatus.DELIVERED);i.setDeliveredBy(scope.currentEmployee());i.setDeliveredAt(Instant.now());repository.save(i);audit.record("SCORE_DELIVERED","score","ScoreItem",id,null,Map.of("status","DELIVERED"));return map(i);}
 private ScoreItem find(UUID id){return repository.findById(id).filter(x->x.getDeletedAt()==null).orElseThrow(()->new ResourceNotFoundException("Score item not found"));}private void draft(ScoreItem i){if(i.getStatus()!=ScoreItemStatus.DRAFT)throw new ConflictException("Only a draft score item can be edited");}
 private Response map(ScoreItem i){return new Response(i.getId(),i.getClazz().getId(),i.getTitle(),i.getMaxScore(),i.getScoreDate(),i.getNote(),i.getStatus(),i.getRecords().stream().map(r->new RecordResponse(r.getStudent().getId(),r.getScore(),r.getComment(),r.getGradedBy().getId(),r.getGradedAt())).toList(),i.getDeliveredAt(),i.getVersion());}
}
