services:
  postgres:
    image: postgres:17
    container_name: apix-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - apix_postgres_data:/var/lib/postgresql/data

volumes:
  apix_postgres_data: