package com.apixenglish.center.modules.videodelivery.controller;
import com.apixenglish.center.common.response.*; import com.apixenglish.center.modules.media.entity.VideoType;
import com.apixenglish.center.modules.videodelivery.dto.VideoDeliveryDtos.*; import com.apixenglish.center.modules.videodelivery.entity.VideoDeliveryStatus;
import com.apixenglish.center.modules.videodelivery.service.VideoDeliveryService; import jakarta.validation.Valid; import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.*; import org.springframework.data.web.PageableDefault; import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.time.LocalDate; import java.util.*;
@RestController @RequestMapping("/api/v1/video-deliveries") @RequiredArgsConstructor
public class VideoDeliveryController {
 private final VideoDeliveryService service;
 @GetMapping @PreAuthorize("hasAuthority('video-delivery:read')") public ApiResponse<List<DeliveryItem>> list(@RequestParam(required=false)String search,@RequestParam(required=false)UUID batchId,@RequestParam(required=false)UUID classId,@RequestParam(required=false)UUID studentId,@RequestParam(required=false)UUID parentId,@RequestParam(required=false)VideoType videoType,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate targetMonth,@RequestParam(required=false)VideoDeliveryStatus status,@RequestParam(required=false)UUID assignedToEmployeeId,@RequestParam(required=false)UUID sentByEmployeeId,@PageableDefault(size=20,sort="createdAt",direction=Sort.Direction.DESC)Pageable pageable){return ApiResponse.success(service.listDeliveries(search,batchId,classId,studentId,parentId,videoType,targetMonth,status,assignedToEmployeeId,sentByEmployeeId,pageable));}
 @GetMapping("/stats") @PreAuthorize("hasAuthority('video-delivery:read')") public ApiResponse<Stats> stats(@RequestParam(required=false)UUID classId,@RequestParam(required=false)VideoType videoType,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate targetMonth,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate dueDateFrom,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate dueDateTo){return ApiResponse.success(service.stats(classId,videoType,targetMonth,dueDateFrom,dueDateTo));}
 @GetMapping("/{id}") @PreAuthorize("hasAuthority('video-delivery:read')") public ApiResponse<DeliveryDetail> detail(@PathVariable UUID id){return ApiResponse.success(service.detail(id));}
 @PostMapping("/{id}/prepare-message") @PreAuthorize("hasAuthority('video-delivery:prepare-message')") public ApiResponse<PrepareMessageResponse> prepare(@PathVariable UUID id){return ApiResponse.success(service.prepare(id));}
 @PatchMapping("/{id}/copied") @PreAuthorize("hasAuthority('video-delivery:mark-copied')") public ApiResponse<DeliveryDetail> copied(@PathVariable UUID id){return ApiResponse.success(service.copied(id));}
 @PatchMapping("/{id}/opened-zalo") @PreAuthorize("hasAuthority('video-delivery:open-zalo')") public ApiResponse<DeliveryDetail> opened(@PathVariable UUID id){return ApiResponse.success(service.opened(id));}
 @PatchMapping("/{id}/sent") @PreAuthorize("hasAuthority('video-delivery:mark-sent')") public ApiResponse<DeliveryDetail> sent(@PathVariable UUID id,@RequestBody(required=false)NoteRequest request){return ApiResponse.success(service.sent(id,request==null?null:request.note()));}
 @PatchMapping("/{id}/failed") @PreAuthorize("hasAuthority('video-delivery:mark-failed')") public ApiResponse<DeliveryDetail> failed(@PathVariable UUID id,@Valid @RequestBody FailedRequest request){return ApiResponse.success(service.failed(id,request.failedReason()));}
 @PatchMapping("/{id}/skipped") @PreAuthorize("hasAuthority('video-delivery:mark-skipped')") public ApiResponse<DeliveryDetail> skipped(@PathVariable UUID id,@Valid @RequestBody SkippedRequest request){return ApiResponse.success(service.skipped(id,request.skippedReason()));}
 @PatchMapping("/{id}/reopen") @PreAuthorize("hasAuthority('video-delivery:reopen')") public ApiResponse<DeliveryDetail> reopen(@PathVariable UUID id){return ApiResponse.success(service.reopen(id));}
}
