package com.apixenglish.center.modules.media.controller;
import com.apixenglish.center.common.response.*; import com.apixenglish.center.modules.media.dto.VideoDtos.*; import com.apixenglish.center.modules.media.entity.*; import com.apixenglish.center.modules.media.service.MediaVideoService;
import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.data.web.PageableDefault; import org.springframework.format.annotation.DateTimeFormat; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*;
import java.time.LocalDate; import java.util.*;
@RestController @RequestMapping("/api/v1/media/videos") @RequiredArgsConstructor
public class MediaVideoController {
 private final MediaVideoService service;
 @PostMapping("/upload-sessions") @PreAuthorize("hasAuthority('media-video:create-upload-session')") public ApiResponse<UploadSessionCreated> create(@Valid @RequestBody CreateUploadSession request){return ApiResponse.success(service.createSession(request));}
 @GetMapping("/upload-sessions/{uploadToken}") public ApiResponse<UploadSessionPublic> uploadSession(@PathVariable String uploadToken){return ApiResponse.success(service.getUploadSession(uploadToken));}
 @PostMapping("/upload-sessions/{uploadToken}/presign") public ApiResponse<PresignResponse> presign(@PathVariable String uploadToken,@Valid @RequestBody PresignRequest request){return ApiResponse.success(service.presign(uploadToken,request));}
 @PostMapping("/upload-sessions/{uploadToken}/complete") public ApiResponse<CompleteResponse> complete(@PathVariable String uploadToken,@Valid @RequestBody CompleteRequest request){return ApiResponse.success(service.complete(uploadToken,request));}
 @PatchMapping("/upload-sessions/{id}/cancel") @PreAuthorize("hasAuthority('media-video:create-upload-session')") public ApiResponse<Void> cancel(@PathVariable UUID id){service.cancelSession(id);return ApiResponse.success("Upload session cancelled");}
 @GetMapping @PreAuthorize("hasAuthority('media-video:read')") public ApiResponse<List<VideoListItem>> list(@RequestParam(required=false)String search,@RequestParam(required=false)UUID classId,@RequestParam(required=false)UUID studentId,@RequestParam(required=false)VideoType videoType,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate targetMonth,@RequestParam(required=false)MediaVideoStatus status,@RequestParam(required=false)UUID uploadedBy,@RequestParam(required=false)Boolean parentVisible,@PageableDefault(size=20,sort="createdAt",direction=Sort.Direction.DESC)Pageable pageable){return ApiResponse.success(service.list(search,classId,studentId,videoType,targetMonth,status,uploadedBy,parentVisible,pageable));}
 @GetMapping("/{id}") @PreAuthorize("hasAuthority('media-video:read')") public ApiResponse<VideoDetail> detail(@PathVariable UUID id){return ApiResponse.success(service.detail(id));}
 @PatchMapping("/{id}/approve") @PreAuthorize("hasAuthority('media-video:approve')") public ApiResponse<VideoDetail> approve(@PathVariable UUID id,@RequestBody(required=false)ApprovalRequest request){return ApiResponse.success(service.approve(id,request));}
 @PatchMapping("/{id}/reject") @PreAuthorize("hasAuthority('media-video:reject')") public ApiResponse<VideoDetail> reject(@PathVariable UUID id,@Valid @RequestBody RejectRequest request){return ApiResponse.success(service.reject(id,request.reason()));}
 @PostMapping("/{id}/share-links") @PreAuthorize("hasAuthority('media-video:create-share-link')") public ApiResponse<ShareLinkResponse> share(@PathVariable UUID id,@Valid @RequestBody(required=false)ShareLinkRequest request){return ApiResponse.success(service.createShare(id,request));}
 @PatchMapping("/share-links/{id}/revoke") @PreAuthorize("hasAuthority('media-video:revoke-share-link')") public ApiResponse<Void> revoke(@PathVariable UUID id){service.revokeShare(id);return ApiResponse.success("Share link revoked");}
 @PostMapping("/{id}/manual-zalo-message") @PreAuthorize("hasAuthority('manual-zalo:prepare') and hasAuthority('media-video:deliver')") public ApiResponse<ManualZaloResponse> zalo(@PathVariable UUID id,@Valid @RequestBody ManualZaloRequest request){return ApiResponse.success(service.prepareZalo(id,request.parentId()));}
}
