package com.apixenglish.center.modules.classmanagement.controller;
import com.apixenglish.center.common.response.*;import com.apixenglish.center.modules.classmanagement.dto.request.*;import com.apixenglish.center.modules.classmanagement.dto.response.*;import com.apixenglish.center.modules.classmanagement.service.ClassEnrollmentService;import jakarta.validation.Valid;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.*;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import java.time.LocalDate;import java.util.*;
@RestController @RequestMapping("/api/v1/enrollments") @RequiredArgsConstructor public class ClassEnrollmentController{
 private final ClassEnrollmentService service;
 @GetMapping @PreAuthorize("hasAuthority('enrollment:read')")public ApiResponse<List<EnrollmentResponse>> list(@RequestParam(required=false)String search,@RequestParam(required=false)String status,@RequestParam(required=false)UUID classId,@RequestParam(required=false)UUID studentId,@RequestParam(required=false)UUID campusId,@RequestParam(required=false)String source,@RequestParam(required=false)LocalDate enrolledFrom,@RequestParam(required=false)LocalDate enrolledTo,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(defaultValue="enrolledDate,desc")String sort){return ApiResponse.success(service.list(search,status,classId,studentId,campusId,source,enrolledFrom,enrolledTo,pageable(page,size,sort)),"Enrollments retrieved successfully");}
 @GetMapping("/{id}")@PreAuthorize("hasAuthority('enrollment:read')")public ApiResponse<EnrollmentDetailResponse> detail(@PathVariable UUID id){return ApiResponse.success(service.getDetail(id));}
 @PostMapping @ResponseStatus(HttpStatus.CREATED)@PreAuthorize("hasAuthority('enrollment:create')")public ApiResponse<EnrollmentResponse> create(@Valid @RequestBody EnrollStudentRequest r){return ApiResponse.success(service.enrollStudent(r),"Student enrolled successfully");}
 @PutMapping("/{id}")@PreAuthorize("hasAuthority('enrollment:update')")public ApiResponse<EnrollmentResponse> update(@PathVariable UUID id,@Valid @RequestBody UpdateEnrollmentRequest r){return ApiResponse.success(service.update(id,r));}
 @PatchMapping("/{id}/cancel")@PreAuthorize("hasAuthority('enrollment:cancel')")public ApiResponse<EnrollmentResponse> cancel(@PathVariable UUID id,@Valid @RequestBody CancelEnrollmentRequest r){return ApiResponse.success(service.cancel(id,r));}
 @PostMapping("/{id}/transfer")@PreAuthorize("hasAuthority('enrollment:transfer')")public ApiResponse<EnrollmentResponse> transfer(@PathVariable UUID id,@Valid @RequestBody TransferEnrollmentRequest r){return ApiResponse.success(service.transfer(id,r));}
 @PostMapping("/{id}/freeze")@PreAuthorize("hasAuthority('enrollment:freeze')")public ApiResponse<EnrollmentResponse> freeze(@PathVariable UUID id,@Valid @RequestBody FreezeEnrollmentRequest r){return ApiResponse.success(service.freeze(id,r));}
 @PatchMapping("/{id}/complete")@PreAuthorize("hasAuthority('enrollment:complete')")public ApiResponse<EnrollmentResponse> complete(@PathVariable UUID id,@Valid @RequestBody CompleteEnrollmentRequest r){return ApiResponse.success(service.complete(id,r));}
 @GetMapping("/student/{id}")@PreAuthorize("hasAuthority('enrollment:read')")public ApiResponse<List<EnrollmentResponse>> byStudent(@PathVariable UUID id){return ApiResponse.success(service.getEnrollmentsByStudent(id));}
 @GetMapping("/class/{id}")@PreAuthorize("hasAuthority('enrollment:read')")public ApiResponse<List<EnrollmentResponse>> byClass(@PathVariable UUID id){return ApiResponse.success(service.getEnrollmentsByClass(id));}
 private Pageable pageable(int page,int size,String value){String[]p=value.split(",",2);Set<String>allowed=Set.of("enrolledDate","startDate","status","enrollmentCode","createdAt");String field=allowed.contains(p[0])?p[0]:"enrolledDate";Sort.Direction direction=p.length>1&&"asc".equalsIgnoreCase(p[1])?Sort.Direction.ASC:Sort.Direction.DESC;return PageRequest.of(Math.max(0,page),Math.min(Math.max(size,1),100),Sort.by(direction,field));}
}
