package com.apixenglish.center.modules.learningreport.service;
import com.apixenglish.center.common.exception.*;import com.apixenglish.center.modules.audit.service.AuditService;import com.apixenglish.center.modules.classmanagement.entity.Clazz;import com.apixenglish.center.modules.classmanagement.repository.*;import com.apixenglish.center.modules.classmanagement.service.ClassScopeGuard;import com.apixenglish.center.modules.employee.entity.Employee;import com.apixenglish.center.modules.learningreport.dto.LearningReportDtos.*;import com.apixenglish.center.modules.learningreport.entity.*;import com.apixenglish.center.modules.learningreport.repository.LearningReportRepository;import com.apixenglish.center.modules.student.entity.Student;import com.apixenglish.center.modules.student.repository.StudentRepository;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.Instant;import java.util.*;
@Service @RequiredArgsConstructor public class LearningReportService{private final LearningReportRepository repository;private final StudentRepository students;private final ClazzRepository classes;private final ClassEnrollmentRepository enrollments;private final ClassScopeGuard scope;private final AuditService audit;
 @Transactional public Response create(Upsert r){validate(r);Employee e=scope.requireAssigned(r.classId());Student s=students.findById(r.studentId()).filter(x->x.getDeletedAt()==null).orElseThrow(()->new ResourceNotFoundException("Student not found"));Clazz c=classes.findById(r.classId()).filter(x->x.getDeletedAt()==null).orElseThrow(()->new ResourceNotFoundException("Class not found"));StudentLearningReport x=StudentLearningReport.builder().student(s).clazz(c).status(LearningReportStatus.DRAFT).preparedBy(e).build();copy(x,r);x=repository.save(x);audit.record("LEARNING_REPORT_CREATED","learning_report","StudentLearningReport",x.getId(),null,Map.of("status","DRAFT"));return map(x);}
 @Transactional(readOnly=true) public Page<Response> list(UUID classId,UUID studentId,Pageable p){return repository.search(classId,studentId,p).map(this::map);}@Transactional(readOnly=true)public Response get(UUID id){return map(find(id));}
 @Transactional public Response update(UUID id,Upsert r){validate(r);StudentLearningReport x=find(id);scope.requireAssigned(x.getClazz().getId());if(x.getStatus()!=LearningReportStatus.DRAFT&&x.getStatus()!=LearningReportStatus.REJECTED)throw new ConflictException("Only draft or rejected reports can be edited");if(!x.getStudent().getId().equals(r.studentId())||!x.getClazz().getId().equals(r.classId()))throw new BusinessException("Student and class cannot be changed","REPORT_SCOPE_IMMUTABLE");copy(x,r);x.setStatus(LearningReportStatus.DRAFT);x.setRejectionReason(null);audit.record("LEARNING_REPORT_UPDATED","learning_report","StudentLearningReport",id,null,Map.of("status","DRAFT"));return map(repository.save(x));}
 @Transactional public Response submit(UUID id){StudentLearningReport x=find(id);scope.requireAssigned(x.getClazz().getId());require(x,LearningReportStatus.DRAFT);x.setStatus(LearningReportStatus.SUBMITTED);return action(x,"LEARNING_REPORT_SUBMITTED");}
 @Transactional public Response approve(UUID id){StudentLearningReport x=find(id);require(x,LearningReportStatus.SUBMITTED);x.setStatus(LearningReportStatus.APPROVED);x.setApprovedBy(scope.currentEmployee());x.setApprovedAt(Instant.now());return action(x,"LEARNING_REPORT_APPROVED");}
 @Transactional public Response reject(UUID id,String reason){StudentLearningReport x=find(id);require(x,LearningReportStatus.SUBMITTED);x.setStatus(LearningReportStatus.REJECTED);x.setApprovedBy(scope.currentEmployee());x.setApprovedAt(Instant.now());x.setRejectionReason(reason);return action(x,"LEARNING_REPORT_REJECTED");}
 @Transactional public Response deliver(UUID id){StudentLearningReport x=find(id);require(x,LearningReportStatus.APPROVED);x.setStatus(LearningReportStatus.DELIVERED);x.setDeliveredBy(scope.currentEmployee());x.setDeliveredAt(Instant.now());return action(x,"LEARNING_REPORT_DELIVERED");}
 private void validate(Upsert r){if(r.periodEnd().isBefore(r.periodStart()))throw new BusinessException("Period end must be on or after period start","INVALID_REPORT_PERIOD");if(!enrollments.existsByStudentIdAndClazzIdAndStatusAndDeletedAtIsNull(r.studentId(),r.classId(),"ACTIVE"))throw new BusinessException("Student is not actively enrolled in this class","STUDENT_NOT_IN_CLASS");}
 private void copy(StudentLearningReport x,Upsert r){x.setReportType(r.reportType());x.setPeriodStart(r.periodStart());x.setPeriodEnd(r.periodEnd());x.setLearningSummary(r.learningSummary());x.setAttitudeSummary(r.attitudeSummary());x.setImprovementNotes(r.improvementNotes());x.setRecommendation(r.recommendation());x.setInternalNote(r.internalNote());}
 private StudentLearningReport find(UUID id){return repository.findById(id).filter(x->x.getDeletedAt()==null).orElseThrow(()->new ResourceNotFoundException("Learning report not found"));}private void require(StudentLearningReport x,LearningReportStatus s){if(x.getStatus()!=s)throw new ConflictException("Learning report cannot transition from "+x.getStatus());}private Response action(StudentLearningReport x,String a){repository.save(x);audit.record(a,"learning_report","StudentLearningReport",x.getId(),null,Map.of("status",x.getStatus().name()));return map(x);}private Response map(StudentLearningReport x){return new Response(x.getId(),x.getStudent().getId(),x.getClazz().getId(),x.getReportType(),x.getPeriodStart(),x.getPeriodEnd(),x.getLearningSummary(),x.getAttitudeSummary(),x.getImprovementNotes(),x.getRecommendation(),x.getInternalNote(),x.getStatus(),x.getPreparedBy().getId(),x.getApprovedBy()==null?null:x.getApprovedBy().getId(),x.getApprovedAt(),x.getRejectionReason(),x.getDeliveredAt(),x.getVersion());}}
